### ISSUE TITLE
python>=3.9 and numpy>=1.22 required

### ISSUE THREAD

**Issue by isuruf** [inducer/boxtree#63]
Because of the line https://github.com/inducer/boxtree/blob/cacf6eb991bdf61cbfd65d2d099223c41e907f62/boxtree/tools.py#L919

If python <3.9, I get,
```python
  File "/home/idf2/miniconda3/envs/py38/lib/python3.8/site-packages/boxtree/tools.py", line 919, in <module>
    coord_dtype: np.dtype[Any], dimensions: int) -> np.dtype[Any]:
TypeError: Type subscription requires python >= 3.9
```

If numpy<1.22, I get,
```python
>>> np.dtype[Any]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

**Comment by inducer** [comment]
cf. #65
